name: Generate README.md

on:
  push:
    branches:
      - master
    paths:
      - 'README.md.template'
  workflow_dispatch:

defaults:
  run:
    shell: bash --login {0}

permissions:
  contents: write

jobs:
  run-templating:
    runs-on: ubuntu-latest
    steps:
      - uses: EffortGames/action-setup-bash@v1
      - uses: actions/checkout@v2
      - uses: EffortGames/action-template@v1
        with:
          source: 'README.md.template'
          target: 'README.md'
      - run: |
          git config --global user.email "automation@effortgames.nl"
          git config --global user.name "EffortGames Automation"
          git add README.md
          if git commit -m"Update README.md"; then
            git push origin master
          fi
